version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"

  - package-ecosystem: "terraform"
    directory: "/infrastructure/proxmox/environments/prod"
    schedule:
      interval: "weekly"
      day: "tuesday"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"

  - package-ecosystem: "terraform"
    directory: "/infrastructure/proxmox/environments/lab"
    schedule:
      interval: "weekly"
      day: "tuesday"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"

  - package-ecosystem: "terraform"
    directory: "/infrastructure/proxmox/environments/monitoring"
    schedule:
      interval: "weekly"
      day: "tuesday"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
